version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: dev_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - "3306:3306"
    restart: always
    network_mode: bridge
